### ISSUE TITLE
I'm sorry to bother you

### ISSUE THREAD

**Issue by ghost** [AchimPieters/ESP8266-HomeKit-Light-Sensor#1]
I am a college student from China. As you know, 
I can’t go out, because of so 2019 novel coronavirus (2019-nCoV),
And then I searched the project on GitHub and found your artwork.
 I really like it. I watched your forum(www.studiopieters.nl), but I ’m not Clearly for circuit structure，
can you tell me? or give a PCB file if possible, it would be greatly appreciated. Thanks again.

**Comment by AchimPieters** [comment]
Here is the scheme:
https://raw.githubusercontent.com/AchimPieters/ESP8266-HomeKit-Light-Sensor/master/images/Light%20Sensor.png

**Comment by ghost** [comment]
Thank you very much！
